# Generated by Django 3.0.8 on 2020-07-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200709_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
